kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: es-data
  namespace: kube-logging
  labels:
    app: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
